# Generated by Django 3.2.25 on 2024-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MashinData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Niitelsen', models.CharField(default='', max_length=100)),
                ('Uildverlegch', models.CharField(default='', max_length=100)),
                ('Mark', models.CharField(default='', max_length=100)),
                ('Motor_bagtaamj', models.CharField(default='', max_length=100)),
                ('Xrop', models.CharField(default='', max_length=100)),
                ('Joloo', models.CharField(default='', max_length=100)),
                ('Torol', models.CharField(blank=True, max_length=100, null=True)),
                ('Ungu', models.CharField(blank=True, max_length=100, null=True)),
                ('Uildverlesen_on', models.IntegerField(blank=True, null=True)),
                ('Orj_irsen_on', models.IntegerField(default=0)),
                ('Hudulguur', models.CharField(default='', max_length=100)),
                ('Dotor_ungu', models.CharField(blank=True, max_length=100, null=True)),
                ('Lizeng', models.CharField(blank=True, max_length=100, null=True)),
                ('Hayg', models.CharField(blank=True, max_length=100, null=True)),
                ('Hutlugch', models.CharField(blank=True, max_length=100, null=True)),
                ('Yavsan_km', models.CharField(blank=True, max_length=100, null=True)),
                ('Nomer', models.CharField(blank=True, max_length=100, null=True)),
                ('Haalga', models.CharField(blank=True, max_length=100, null=True)),
                ('Une', models.IntegerField(default=0)),
                ('Unique_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mashin_data',
            },
        ),
    ]
